/**
 * @file fsoft.c
 *
 * @brief This source file was generated by cantools version 40.3.0 Sat Aug  2 11:53:55 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "fsoft.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint64_t unpack_left_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint64_t unpack_right_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) >> shift);
}

int fsoft_data_message_pack(
    uint8_t *dst_p,
    const struct fsoft_data_message_t *src_p,
    size_t size)
{
    uint16_t light_level;
    uint8_t fan;
    uint8_t light;
    uint8_t temp;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    fan = (uint8_t)src_p->fan;
    dst_p[0] |= pack_left_shift_u8(fan, 0u, 0x01u);
    light = (uint8_t)src_p->light;
    dst_p[0] |= pack_left_shift_u8(light, 1u, 0x02u);
    temp = (uint8_t)src_p->temp;
    dst_p[1] |= pack_left_shift_u8(temp, 0u, 0xffu);
    light_level = (uint16_t)src_p->light_level;
    dst_p[2] |= pack_left_shift_u16(light_level, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(light_level, 8u, 0xffu);

    return (8);
}

int fsoft_data_message_unpack(
    struct fsoft_data_message_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t light_level;
    uint8_t fan;
    uint8_t light;
    uint8_t temp;

    if (size < 8u) {
        return (-EINVAL);
    }

    fan = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    if ((fan & (1u << 0)) != 0u) {
        fan |= 0xfeu;
    }

    dst_p->fan = (int8_t)fan;
    light = unpack_right_shift_u8(src_p[0], 1u, 0x02u);

    if ((light & (1u << 0)) != 0u) {
        light |= 0xfeu;
    }

    dst_p->light = (int8_t)light;
    temp = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->temp = (int8_t)temp;
    light_level = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    light_level |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->light_level = (int16_t)light_level;

    return (0);
}

int fsoft_data_message_init(struct fsoft_data_message_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct fsoft_data_message_t));

    return 0;
}

int8_t fsoft_data_message_fan_encode(double value)
{
    return (int8_t)(value);
}

double fsoft_data_message_fan_decode(int8_t value)
{
    return ((double)value);
}

bool fsoft_data_message_fan_is_in_range(int8_t value)
{
    return ((value >= -1) && (value <= 0));
}

int8_t fsoft_data_message_light_encode(double value)
{
    return (int8_t)(value);
}

double fsoft_data_message_light_decode(int8_t value)
{
    return ((double)value);
}

bool fsoft_data_message_light_is_in_range(int8_t value)
{
    return ((value >= -1) && (value <= 0));
}

int8_t fsoft_data_message_temp_encode(double value)
{
    return (int8_t)(value);
}

double fsoft_data_message_temp_decode(int8_t value)
{
    return ((double)value);
}

bool fsoft_data_message_temp_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int16_t fsoft_data_message_light_level_encode(double value)
{
    return (int16_t)(value);
}

double fsoft_data_message_light_level_decode(int16_t value)
{
    return ((double)value);
}

bool fsoft_data_message_light_level_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int fsoft_request_pack(
    uint8_t *dst_p,
    const struct fsoft_request_t *src_p,
    size_t size)
{
    uint64_t req_signal;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    req_signal = (uint64_t)src_p->req_signal;
    dst_p[0] |= pack_left_shift_u64(req_signal, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(req_signal, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(req_signal, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(req_signal, 24u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(req_signal, 32u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(req_signal, 40u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(req_signal, 48u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(req_signal, 56u, 0xffu);

    return (8);
}

int fsoft_request_unpack(
    struct fsoft_request_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint64_t req_signal;

    if (size < 8u) {
        return (-EINVAL);
    }

    req_signal = unpack_right_shift_u64(src_p[0], 0u, 0xffu);
    req_signal |= unpack_left_shift_u64(src_p[1], 8u, 0xffu);
    req_signal |= unpack_left_shift_u64(src_p[2], 16u, 0xffu);
    req_signal |= unpack_left_shift_u64(src_p[3], 24u, 0xffu);
    req_signal |= unpack_left_shift_u64(src_p[4], 32u, 0xffu);
    req_signal |= unpack_left_shift_u64(src_p[5], 40u, 0xffu);
    req_signal |= unpack_left_shift_u64(src_p[6], 48u, 0xffu);
    req_signal |= unpack_left_shift_u64(src_p[7], 56u, 0xffu);
    dst_p->req_signal = (int64_t)req_signal;

    return (0);
}

int fsoft_request_init(struct fsoft_request_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct fsoft_request_t));

    return 0;
}

int64_t fsoft_request_req_signal_encode(double value)
{
    return (int64_t)(value);
}

double fsoft_request_req_signal_decode(int64_t value)
{
    return ((double)value);
}

bool fsoft_request_req_signal_is_in_range(int64_t value)
{
    (void)value;

    return (true);
}

int fsoft_response_pack(
    uint8_t *dst_p,
    const struct fsoft_response_t *src_p,
    size_t size)
{
    uint64_t res_signal;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    res_signal = (uint64_t)src_p->res_signal;
    dst_p[0] |= pack_left_shift_u64(res_signal, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(res_signal, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(res_signal, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(res_signal, 24u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(res_signal, 32u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(res_signal, 40u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(res_signal, 48u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(res_signal, 56u, 0xffu);

    return (8);
}

int fsoft_response_unpack(
    struct fsoft_response_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint64_t res_signal;

    if (size < 8u) {
        return (-EINVAL);
    }

    res_signal = unpack_right_shift_u64(src_p[0], 0u, 0xffu);
    res_signal |= unpack_left_shift_u64(src_p[1], 8u, 0xffu);
    res_signal |= unpack_left_shift_u64(src_p[2], 16u, 0xffu);
    res_signal |= unpack_left_shift_u64(src_p[3], 24u, 0xffu);
    res_signal |= unpack_left_shift_u64(src_p[4], 32u, 0xffu);
    res_signal |= unpack_left_shift_u64(src_p[5], 40u, 0xffu);
    res_signal |= unpack_left_shift_u64(src_p[6], 48u, 0xffu);
    res_signal |= unpack_left_shift_u64(src_p[7], 56u, 0xffu);
    dst_p->res_signal = (int64_t)res_signal;

    return (0);
}

int fsoft_response_init(struct fsoft_response_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct fsoft_response_t));

    return 0;
}

int64_t fsoft_response_res_signal_encode(double value)
{
    return (int64_t)(value);
}

double fsoft_response_res_signal_decode(int64_t value)
{
    return ((double)value);
}

bool fsoft_response_res_signal_is_in_range(int64_t value)
{
    (void)value;

    return (true);
}
