/**
 * @file fsoft.h
 *
 * @brief This header file was generated by cantools version 40.3.0 Sat Aug  2 11:53:55 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef FSOFT_H
#define FSOFT_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define FSOFT_DATA_MESSAGE_FRAME_ID (0x200u)
#define FSOFT_REQUEST_FRAME_ID (0x769u)
#define FSOFT_RESPONSE_FRAME_ID (0x768u)

/* Frame lengths in bytes. */
#define FSOFT_DATA_MESSAGE_LENGTH (8u)
#define FSOFT_REQUEST_LENGTH (8u)
#define FSOFT_RESPONSE_LENGTH (8u)

/* Extended or standard frame types. */
#define FSOFT_DATA_MESSAGE_IS_EXTENDED (0)
#define FSOFT_REQUEST_IS_EXTENDED (0)
#define FSOFT_RESPONSE_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */
#define FSOFT_DATA_MESSAGE_FAN_OFF_CHOICE (0)
#define FSOFT_DATA_MESSAGE_FAN_ON_CHOICE (1)

#define FSOFT_DATA_MESSAGE_LIGHT_OFF_CHOICE (0)
#define FSOFT_DATA_MESSAGE_LIGHT_ON_CHOICE (1)

#define FSOFT_DATA_MESSAGE_TEMP_DESCRIPTION_FOR_THE_VALUE__0X0__CHOICE (0)
#define FSOFT_DATA_MESSAGE_TEMP_DESCRIPTION_FOR_THE_VALUE__0X1__CHOICE (1)
#define FSOFT_DATA_MESSAGE_TEMP_DESCRIPTION_FOR_THE_VALUE__0X2__CHOICE (2)
#define FSOFT_DATA_MESSAGE_TEMP_DESCRIPTION_FOR_THE_VALUE__0X3__CHOICE (3)
#define FSOFT_DATA_MESSAGE_TEMP_DESCRIPTION_FOR_THE_VALUE__0X4__CHOICE (4)
#define FSOFT_DATA_MESSAGE_TEMP_DESCRIPTION_FOR_THE_VALUE__0X5__CHOICE (5)
#define FSOFT_DATA_MESSAGE_TEMP_DESCRIPTION_FOR_THE_VALUE__0X6__CHOICE (6)
#define FSOFT_DATA_MESSAGE_TEMP_DESCRIPTION_FOR_THE_VALUE__0X7__CHOICE (7)

#define FSOFT_DATA_MESSAGE_LIGHT_LEVEL_DESCRIPTION_FOR_THE_VALUE__0X0__CHOICE (0)
#define FSOFT_DATA_MESSAGE_LIGHT_LEVEL_DESCRIPTION_FOR_THE_VALUE__0X1__CHOICE (1)
#define FSOFT_DATA_MESSAGE_LIGHT_LEVEL_DESCRIPTION_FOR_THE_VALUE__0X2__CHOICE (2)
#define FSOFT_DATA_MESSAGE_LIGHT_LEVEL_DESCRIPTION_FOR_THE_VALUE__0X3__CHOICE (3)
#define FSOFT_DATA_MESSAGE_LIGHT_LEVEL_DESCRIPTION_FOR_THE_VALUE__0X4__CHOICE (4)
#define FSOFT_DATA_MESSAGE_LIGHT_LEVEL_DESCRIPTION_FOR_THE_VALUE__0X5__CHOICE (5)
#define FSOFT_DATA_MESSAGE_LIGHT_LEVEL_DESCRIPTION_FOR_THE_VALUE__0X6__CHOICE (6)
#define FSOFT_DATA_MESSAGE_LIGHT_LEVEL_DESCRIPTION_FOR_THE_VALUE__0X7__CHOICE (7)
#define FSOFT_DATA_MESSAGE_LIGHT_LEVEL_DESCRIPTION_FOR_THE_VALUE__0X8__CHOICE (8)
#define FSOFT_DATA_MESSAGE_LIGHT_LEVEL_DESCRIPTION_FOR_THE_VALUE__0X9__CHOICE (9)
#define FSOFT_DATA_MESSAGE_LIGHT_LEVEL_DESCRIPTION_FOR_THE_VALUE__0X_A__CHOICE (10)
#define FSOFT_DATA_MESSAGE_LIGHT_LEVEL_DESCRIPTION_FOR_THE_VALUE__0X_B__CHOICE (11)
#define FSOFT_DATA_MESSAGE_LIGHT_LEVEL_DESCRIPTION_FOR_THE_VALUE__0X_C__CHOICE (12)
#define FSOFT_DATA_MESSAGE_LIGHT_LEVEL_DESCRIPTION_FOR_THE_VALUE__0X_D__CHOICE (13)
#define FSOFT_DATA_MESSAGE_LIGHT_LEVEL_DESCRIPTION_FOR_THE_VALUE__0X_E__CHOICE (14)
#define FSOFT_DATA_MESSAGE_LIGHT_LEVEL_DESCRIPTION_FOR_THE_VALUE__0X_F__CHOICE (15)

/* Frame Names. */
#define FSOFT_DATA_MESSAGE_NAME "data_message"
#define FSOFT_REQUEST_NAME "request"
#define FSOFT_RESPONSE_NAME "response"

/* Signal Names. */
#define FSOFT_DATA_MESSAGE_FAN_NAME "fan"
#define FSOFT_DATA_MESSAGE_LIGHT_NAME "light"
#define FSOFT_DATA_MESSAGE_TEMP_NAME "temp"
#define FSOFT_DATA_MESSAGE_LIGHT_LEVEL_NAME "light_level"
#define FSOFT_REQUEST_REQ_SIGNAL_NAME "req_signal"
#define FSOFT_RESPONSE_RES_SIGNAL_NAME "res_signal"

/**
 * Signals in message data_message.
 *
 * All signal values are as on the CAN bus.
 */
struct fsoft_data_message_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    int8_t fan;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    int8_t light;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    int8_t temp;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    int16_t light_level;
};

/**
 * Signals in message request.
 *
 * All signal values are as on the CAN bus.
 */
struct fsoft_request_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    int64_t req_signal;
};

/**
 * Signals in message response.
 *
 * All signal values are as on the CAN bus.
 */
struct fsoft_response_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    int64_t res_signal;
};

/**
 * Pack message data_message.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int fsoft_data_message_pack(
    uint8_t *dst_p,
    const struct fsoft_data_message_t *src_p,
    size_t size);

/**
 * Unpack message data_message.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int fsoft_data_message_unpack(
    struct fsoft_data_message_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from data_message.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int fsoft_data_message_init(struct fsoft_data_message_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t fsoft_data_message_fan_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fsoft_data_message_fan_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fsoft_data_message_fan_is_in_range(int8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t fsoft_data_message_light_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fsoft_data_message_light_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fsoft_data_message_light_is_in_range(int8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t fsoft_data_message_temp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fsoft_data_message_temp_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fsoft_data_message_temp_is_in_range(int8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t fsoft_data_message_light_level_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fsoft_data_message_light_level_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fsoft_data_message_light_level_is_in_range(int16_t value);

/**
 * Pack message request.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int fsoft_request_pack(
    uint8_t *dst_p,
    const struct fsoft_request_t *src_p,
    size_t size);

/**
 * Unpack message request.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int fsoft_request_unpack(
    struct fsoft_request_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from request.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int fsoft_request_init(struct fsoft_request_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int64_t fsoft_request_req_signal_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fsoft_request_req_signal_decode(int64_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fsoft_request_req_signal_is_in_range(int64_t value);

/**
 * Pack message response.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int fsoft_response_pack(
    uint8_t *dst_p,
    const struct fsoft_response_t *src_p,
    size_t size);

/**
 * Unpack message response.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int fsoft_response_unpack(
    struct fsoft_response_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from response.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int fsoft_response_init(struct fsoft_response_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int64_t fsoft_response_res_signal_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fsoft_response_res_signal_decode(int64_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fsoft_response_res_signal_is_in_range(int64_t value);


#ifdef __cplusplus
}
#endif

#endif
