#include "motor.h"
#include "sdk_project_config.h"
#include "device_registers.h"
#include "ftm_pwm_driver.h"
#include "pins_driver.h"
#include "osif.h"

/* State object required by the FTM SDK driver. */
static ftm_state_t s_ftmState;

/* Extern declarations for configuration structures generated by NXP ConfigTools. */
extern ftm_pwm_param_t                flexTimer_pwm_1_PwmConfig;
extern ftm_independent_ch_param_t     flexTimer_pwm_1_IndependentChannelsConfig[];
extern ftm_user_config_t              flexTimer_pwm_1_InitConfig;

/**
 * @brief Calculates the PWM period in timer ticks.
 * @details Processing Logic:
 * 1. Gets the base address of the FTM instance.
 * 2. Checks if the timer is in Center-aligned PWM (CPWMS) mode.
 * 3. In CPWMS mode, the period is equal to the value in the MOD register.
 * 4. In Edge-aligned mode, the period is (MOD + 1).
 * This ensures correct duty cycle calculations regardless of PWM alignment.
 * @return The total number of ticks in one PWM period.
 */
static inline uint16_t prv_get_period_ticks(void)
{
    extern FTM_Type * const g_ftmBase[FTM_INSTANCE_COUNT];
    FTM_Type *ftm_instance = g_ftmBase[MOTOR_FTM_INSTANCE];
    const bool is_center_aligned = ((ftm_instance->SC & FTM_SC_CPWMS_MASK) != 0u);

    return (uint16_t)(is_center_aligned ? (ftm_instance->MOD) : (ftm_instance->MOD + 1u));
}

/**
 * @brief Sets the state of the H-bridge direction control pins (IN1, IN2).
 * @details Processing Logic:
 * A switch statement translates the logical motor direction into the
 * physical HIGH/LOW states required by the H-bridge driver IC.
 * @param direction The desired motor direction.
 */
static inline void prv_write_dir_pins(motor_dir_t direction)
{
    switch (direction)
    {
        case MOTOR_DIR_FORWARD: /* IN1=HIGH, IN2=LOW */
            PINS_DRV_WritePin(MOTOR_IN1_GPIO, MOTOR_IN1_PIN, 1u);
            PINS_DRV_WritePin(MOTOR_IN2_GPIO, MOTOR_IN2_PIN, 0u);
            break;
        case MOTOR_DIR_REVERSE: /* IN1=LOW, IN2=HIGH */
            PINS_DRV_WritePin(MOTOR_IN1_GPIO, MOTOR_IN1_PIN, 0u);
            PINS_DRV_WritePin(MOTOR_IN2_GPIO, MOTOR_IN2_PIN, 1u);
            break;
        case MOTOR_DIR_BRAKE:   /* IN1=HIGH, IN2=HIGH */
            PINS_DRV_WritePin(MOTOR_IN1_GPIO, MOTOR_IN1_PIN, 1u);
            PINS_DRV_WritePin(MOTOR_IN2_GPIO, MOTOR_IN2_PIN, 1u);
            break;
        case MOTOR_DIR_COAST:   /* IN1=LOW, IN2=LOW */
        default:
            PINS_DRV_WritePin(MOTOR_IN1_GPIO, MOTOR_IN1_PIN, 0u);
            PINS_DRV_WritePin(MOTOR_IN2_GPIO, MOTOR_IN2_PIN, 0u);
            break;
    }
}

/**
 * @brief Initializes the motor driver.
 * @details Processing Logic:
 * 1. Sets direction pins to a known safe state (COAST: IN1=0, IN2=0).
 * 2. If a standby pin is used, it is driven HIGH to enable the H-bridge IC.
 * 3. Initializes the FTM peripheral instance.
 * 4. Configures the specified FTM channel for PWM operation.
 * 5. Sets the initial duty cycle to 0 ticks (0% speed).
 * 6. Sets the initial direction to COAST.
 */
void Motor_Init(void)
{
    prv_write_dir_pins(MOTOR_DIR_COAST);

#if MOTOR_HAS_STBY
    PINS_DRV_WritePin(MOTOR_STBY_GPIO, MOTOR_STBY_PIN, 1u); /* Bring H-bridge out of standby */
#endif

    (void)FTM_DRV_Init(MOTOR_FTM_INSTANCE, &flexTimer_pwm_1_InitConfig, &s_ftmState);
    (void)FTM_DRV_InitPwm(MOTOR_FTM_INSTANCE, &flexTimer_pwm_1_PwmConfig);

    (void)FTM_DRV_UpdatePwmChannel(MOTOR_FTM_INSTANCE,
                                   MOTOR_FTM_CHANNEL,
                                   FTM_PWM_UPDATE_IN_TICKS,
                                   0u, /* Initial duty cycle in ticks */
                                   0u, /* secondEdge (not used for independent channels) */
                                   true); /* trigger a software sync */
}

/**
 * @brief Sets the rotational direction of the motor.
 * @details Processing Logic:
 * Simply calls the private helper function `prv_write_dir_pins` to update
 * the GPIO states according to the selected direction.
 */
void Motor_SetDirection(motor_dir_t direction)
{
    prv_write_dir_pins(direction);
}

/**
 * @brief Sets the motor speed as a permille value (parts per thousand).
 * @details Processing Logic:
 * 1. Saturates the input `permille` value to a maximum of 1000.
 * 2. Gets the current PWM period in ticks using `prv_get_period_ticks()`.
 * 3. Calculates the required duty cycle in ticks using the formula:
 * ticks = (period_ticks * permille) / 1000.
 * 32-bit arithmetic is used to prevent overflow during calculation.
 * 4. Saturates the calculated ticks to ensure it does not exceed the period.
 * 5. Updates the FTM PWM channel with the new duty cycle in ticks.
 */
void Motor_SetSpeed(uint16_t speed)
{
    if (speed > 1000u) {
        speed = 1000u;
    }

    const uint16_t period_ticks = prv_get_period_ticks();
    uint32_t duty_ticks = ((uint32_t)period_ticks * (uint32_t)speed) / 1000u;

    if (duty_ticks > period_ticks) {
        duty_ticks = period_ticks;
    }

    (void)FTM_DRV_UpdatePwmChannel(MOTOR_FTM_INSTANCE,
                                   MOTOR_FTM_CHANNEL,
                                   FTM_PWM_UPDATE_IN_TICKS,
                                   (uint16_t)duty_ticks,
                                   0u, /* secondEdge */
                                   true); /* software sync */
}

/**
 * @brief Stops the motor safely.
 * @details Processing Logic:
 * 1. Updates the PWM channel duty cycle to 0 ticks, stopping power delivery.
 * 2. Sets the H-bridge direction to COAST, allowing the motor to spin down freely.
 */
void Motor_Stop(void)
{
    (void)FTM_DRV_UpdatePwmChannel(MOTOR_FTM_INSTANCE,
                                   MOTOR_FTM_CHANNEL,
                                   FTM_PWM_UPDATE_IN_TICKS,
                                   0u, 0u, true);
    prv_write_dir_pins(MOTOR_DIR_COAST);
}

/**
 * @brief De-initializes the motor driver.
 * @details Processing Logic:
 * 1. Calls `Motor_Stop()` to ensure the motor is in a safe, unpowered state.
 * 2. If a standby pin is used, it is driven LOW to put the H-bridge IC into a
 * low-power standby mode.
 * 3. The FTM de-initialization is commented out by default, as the FTM peripheral
 * might be shared by other components. It can be enabled if exclusive control is desired.
 */
void Motor_Deinit(void)
{
    Motor_Stop();

#if MOTOR_HAS_STBY
    PINS_DRV_WritePin(MOTOR_STBY_GPIO, MOTOR_STBY_PIN, 0u); /* Enter standby mode */
#endif

    // FTM_DRV_Deinit(MOTOR_FTM_INSTANCE);
}
